# Generated by Django 3.1.13 on 2021-07-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The full title of the article including its subtitle', max_length=250)),
                ('abstract', models.TextField(blank=True, help_text='The abstract of the article', max_length=2000, null=True)),
                ('license', models.URLField(blank=True, help_text='The full web address for a license page such as a https://creativecommons.org/licenses/by/4.0/', null=True)),
                ('given_name', models.CharField(blank=True, help_text='First or given name of person (leave blank for organizations)', max_length=100, null=True)),
                ('family_name', models.CharField(help_text='Last or family name of person, or name of organization as contributor', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
