# Generated by Django 3.1.13 on 2021-07-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(default='10.0000/0', help_text='The Digital Object Identifier (e.g. 10.3998/ergo.12405314.0002.002)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='The full title of the article including its subtitle', max_length=255),
        ),
    ]
