# Generated by Django 3.1.13 on 2021-07-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_auto_20210711_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='orcid',
            field=models.CharField(blank=True, help_text='The ORCID identifier (e.g. 0000-0003-3230-6090)', max_length=255, null=True, verbose_name='ORCID'),
        ),
    ]
