# Generated by Django 3.1.13 on 2021-07-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_auto_20210711_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
