# Generated by Django 3.1.13 on 2021-07-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_auto_20210711_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='A contributor to the article', to='lookup.Contributor'),
        ),
    ]
