# Generated by Django 3.1.13 on 2021-07-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0006_auto_20210711_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.article')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.contributor')),
            ],
        ),

        # migrations.AlterField(
        #     model_name='article',
        #     name='contributors',
        #     field=models.ManyToManyField(blank=True, help_text='A contributor to the article', through='lookup.Contribution', to='lookup.Contributor'),
        # ),

        # https://stackoverflow.com/questions/26927705/django-migration-error-you-cannot-alter-to-or-from-m2m-fields-or-add-or-remove

        migrations.RemoveField(
            model_name='article',
            name='contributors',
        ),
        migrations.AddField(
            model_name='article',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='A contributor to the article', through='lookup.Contribution', to='lookup.Contributor'),
        ),

    ]
