# Generated by Django 3.1.13 on 2021-07-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0007_auto_20210711_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='The full web address for a license page such as a https://creativecommons.org/licenses/by/4.0/', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookup.license'),
        ),
    ]
