# Generated by Django 3.1 on 2021-07-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_auto_20210711_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title']},
        ),
    ]
